declare module '*.css';
declare module '*.less';
declare module '*.sass';
declare module '*.scss';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.bmp';
declare module '*.tiff';
//使用“模块”声明您的 css 文件
